# Generated by Django 5.2.4 on 2025-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('의류', '의류'), ('굿즈', '굿즈'), ('잡화', '잡화')], max_length=20)),
            ],
        ),
    ]
